routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\ApplicationsController;
use App\Http\Controllers\ServicePriceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('login', [LoginController::class, 'login'])->name('login');

Route::get('/', function () {
    return redirect('certify-user');
    // return view('welcome');
});

Route::group(['namespace' => 'App\Http\Controllers'], function () {
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('login', "LoginController@login")->name('login');
        Route::get('logout', "LoginController@logout")->name('logout');
        Route::post('authenticate', "LoginController@authenticate")->name('authenticate');
    });
});

Route::get('certify-user', function () {
    $servicePrices = \App\Models\ServicePrice::where('is_active', 1)->get();
    return view('apply')->with(['service_prices' => $servicePrices]);
});

Route::post('certify-user', [ApplicationsController::class, 'store']);
Route::resource('applications', ApplicationsController::class);
Route::post('approve-user', [ApplicationsController::class, 'approve'])->name('approve');
Route::post('accept-user', [ApplicationsController::class, 'accept'])->name('accept');
Route::post('reject-user', [ApplicationsController::class, 'reject'])->name('reject');

Route::resource('prices', ServicePriceController::class);

app/Models/Applications.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\ApplicationImages;
use App\Models\ApplicationGraduations;
use App\Models\ServicePrice;

class Applications extends Model
{
    use HasFactory;

    const PROFILE_IMAGE_PATH = 'applicant/profile';
    protected $table = 'applications';
    public $primaryKey = "id";
    protected $guarded = [];
    protected $fillable = ['first_name', 'last_name', 'email', 'phone', 'country'];

    function applicationImages(){
        return $this->hasOne(ApplicationImages::class, 'application_id', 'id');
    }

    function serviceInvoice(){
        return $this->hasOne(ServicePrice::class, 'id', 'service_price_id');
    }

    function applicationGraduations(){
        return $this->hasMany(ApplicationGraduations::class, 'application_id', 'id');
    }

    function getFullNameAttribute() : string {
        return $this->first_name . ' ' . $this->last_name;
    }
}

app/Models/ServicePrice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ServicePrice extends Model
{
    use HasFactory;
    protected $table = 'service_price';
    public $primaryKey = "id";
    protected $fillable = ['title', 'price', 'vat', 'vat_type', 'type'];

    function getTotalAttribute() {
        if ($this->getAttribute('vat_type') == 'fixed') {
            return ($this->price + $this->vat);
        } else {
            $vat = (($this->vat / $this->price) * 100);
            return round(($this->price + $vat), 2);
        }
    }
}

resources/views/templates/requestApprove.blade.php
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Request Approved</title>
  </head>
  <body class="">
    <table border="0" cellpadding="5" cellspacing="0" width="400">
        <tr>
            <th><h1>eServices</h1></th>
            <th align="right"><h6>Invoice</h6></th>
        </tr>
        <tr>
            <th></th>
            <th align="right">{{ date('d M, Y') }}</th>
        </tr>
        <tr style="border-bottom: 2px solid #000;">
            <td></td>
            <td align="right">Invoice {{ str_pad($data->id, 5, 0, STR_PAD_LEFT) }}</td>
        </tr>
        <tr>
            <td align="left" colspan="2"><b>Dear {{ ucfirst($data->full_name) }},</b></td>
        </tr>
        <tr>
            <td align="left">{{ $data->serviceInvoice->title }}</td>
            <td align="right">{{ $data->serviceInvoice->price }}</td>
        </tr>
        <tr>
            <td align="left">
                Vat
            </td>
            <td align="right">{{ $data->serviceInvoice->vat }}</td>
        </tr>
        <tr>
            <td align="right">Total</td>
            <td align="right">{{ $data->serviceInvoice->total }}</td>
        </tr>
        <tr>
            <td align="left" colspan="2">
                Thank you - eServices
            </td>
        </tr>
    </table>
  </body>
</html>